version: '3'
services:

  redis:
    image: redis:3.2
    command:
      - redis-server
      - /redis.d/redis.conf
    volumes:
      - ./data:/data:rw
      - ./redis.d:/redis.d:ro
    network_mode: host